import { useEffect, useMemo, useState } from 'react'
import { useComplaintStore } from '../../store/complaintStore'
import { useProductionStore } from '../../store/productionStore'
import { apiFetch } from '../../lib/api'
import { manilaDateYmd } from '../../lib/date'
import { ErrorBanner, PageLoader } from '../../components/ui/Feedback'

const esc=v=>`"${String(v??'').replaceAll('"','""')}"`
const today=()=>manilaDateYmd()
export default function CommercialExportCenterPage(){
 const complaints=useComplaintStore(s=>s.complaints),fetchComplaints=useComplaintStore(s=>s.fetchComplaints); const schedules=useProductionStore(s=>s.reportSchedules),runs=useProductionStore(s=>s.reportRuns),loadSchedules=useProductionStore(s=>s.loadReportSchedules),createSchedule=useProductionStore(s=>s.createReportSchedule),runSchedule=useProductionStore(s=>s.runReportSchedule),deleteSchedule=useProductionStore(s=>s.deleteReportSchedule)
 const [filters,setFilters]=useState({from:'',to:today(),status:'all',priority:'all',q:''}),[schedule,setSchedule]=useState({name:'Weekly Complaint Summary',report_type:'complaint_summary',cadence:'weekly'}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{Promise.all([fetchComplaints(),loadSchedules()]).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[fetchComplaints,loadSchedules])
 const scoped=useMemo(()=>complaints.filter(c=>{const d=new Date(c.created_at||c.submitted_at);if(filters.from&&d<new Date(`${filters.from}T00:00:00`))return false;if(filters.to&&d>new Date(`${filters.to}T23:59:59.999`))return false;if(filters.status!=='all'&&c.status!==filters.status)return false;if(filters.priority!=='all'&&c.priority!==filters.priority)return false;const q=filters.q.trim().toLowerCase();return !q||[c.reference_number,c.complaint_type,c.customer_name,c.address,c.zone].some(v=>String(v||'').toLowerCase().includes(q))}),[complaints,filters])
 const exportCsv=async()=>{setError('');try{await apiFetch('/production/exports/log',{method:'POST',body:JSON.stringify({export_type:'complaint_export',format:'csv',row_count:scoped.length,filters})});const headers=['Complaint Reference','Complaint Type','Customer','Priority','Status','Address','Barangay/Zone','Assigned Maintenance Personnel','Submitted','Resolved'];const rows=scoped.map(c=>[c.reference_number,c.complaint_type,c.customer_name,c.priority,c.status,c.address,c.zone,c.assigned_name,c.created_at,c.verified_at||c.completed_at||'']);const blob=new Blob([[headers,...rows].map(r=>r.map(esc).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mrwd-complaint-export-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}catch(e){setError(e.message)}}
 const add=async e=>{e.preventDefault();setBusy(true);try{await createSchedule({...schedule,filters});}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <PageLoader label="Preparing export center..."/>
 return <div className="space-y-5"><div className="page-band wave-header rounded-2xl px-5 py-6 sm:px-6"><p className="text-[11px] font-bold uppercase tracking-widest text-gold-400">Commercial Services Department</p><h1 className="mt-1 font-display text-2xl font-black text-white sm:text-3xl">Export & Scheduled Reports</h1><p className="mt-1 text-sm text-navy-300">Build a filtered complaint dataset, export it, and keep recurring report definitions in one place.</p></div>{error&&<ErrorBanner message={error}/>}<section className="card rounded-xl p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input type="date" value={filters.from} onChange={e=>setFilters(v=>({...v,from:e.target.value}))} className="input-field rounded-lg"/><input type="date" value={filters.to} onChange={e=>setFilters(v=>({...v,to:e.target.value}))} className="input-field rounded-lg"/><select value={filters.status} onChange={e=>setFilters(v=>({...v,status:e.target.value}))} className="input-field rounded-lg"><option value="all">Any Status</option><option value="pending">Pending Review</option><option value="forwarded">Forwarded to ECMD</option><option value="assigned">Assigned</option><option value="in_progress">In Progress</option><option value="awaiting_verification">Awaiting ECMD Verification</option><option value="resolved">Resolved</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option><option value="merged">Merged</option></select><select value={filters.priority} onChange={e=>setFilters(v=>({...v,priority:e.target.value}))} className="input-field rounded-lg"><option value="all">Any Priority</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><input value={filters.q} onChange={e=>setFilters(v=>({...v,q:e.target.value}))} className="input-field rounded-lg" placeholder="Search type, customer, area…"/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-3xl font-black text-navy-900">{scoped.length}</p><p className="text-xs text-gray-500">complaints in export preview</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="btn-primary rounded-lg">Export CSV</button><button onClick={()=>window.print()} className="btn-secondary rounded-lg">Print / Save PDF</button></div></div></section>
 <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="card rounded-xl p-5"><h2 className="font-display font-black text-navy-900">Scheduled Report Definitions</h2><div className="mt-4 space-y-3">{schedules.map(s=><div key={s.id} className="rounded-xl border border-gray-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black text-navy-900">{s.name}</p><p className="mt-1 text-xs text-gray-500">{String(s.report_type).replaceAll('_',' ')} · {s.cadence} · next {s.next_run_at?new Date(s.next_run_at).toLocaleString('en-PH'):'not scheduled'}</p></div><div className="flex gap-2"><button onClick={()=>runSchedule(s.id)} className="btn-secondary rounded-lg text-xs">Run Now</button><button onClick={()=>deleteSchedule(s.id)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700">Delete</button></div></div></div>)}{!schedules.length&&<p className="py-8 text-center text-sm text-gray-400">No scheduled report definitions yet.</p>}</div><h3 className="mt-6 text-xs font-black uppercase tracking-wider text-gray-400">Generated Run Archive</h3><div className="mt-2 space-y-2">{runs.slice(0,10).map(r=><div key={r.id} className="rounded-lg bg-gray-50 p-3 text-xs"><p className="font-black text-gray-800">{String(r.report_type).replaceAll('_',' ')} · {r.row_count} rows</p><p className="mt-1 text-gray-400">{new Date(r.generated_at).toLocaleString('en-PH')}</p></div>)}</div></div><form onSubmit={add} className="card h-fit rounded-xl p-5"><h2 className="font-display font-black text-navy-900">New Schedule</h2><p className="mt-1 text-xs text-gray-500">The current export filters are saved with the report definition.</p><div className="mt-4 space-y-3"><input required minLength="2" value={schedule.name} onChange={e=>setSchedule(v=>({...v,name:e.target.value}))} className="input-field rounded-lg"/><select value={schedule.report_type} onChange={e=>setSchedule(v=>({...v,report_type:e.target.value}))} className="input-field rounded-lg"><option value="complaint_summary">Complaint Summary</option><option value="complaint_export">Complaint Export</option><option value="customer_satisfaction">Customer Satisfaction</option></select><select value={schedule.cadence} onChange={e=>setSchedule(v=>({...v,cadence:e.target.value}))} className="input-field rounded-lg"><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><button disabled={busy} className="btn-primary w-full rounded-lg">{busy?'Saving…':'Save Schedule'}</button></div></form></section></div>
}
